services:
  postgres-user:
    image: postgres:16
    container_name: postgres-user
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - pgdata-user:/var/lib/postgresql/data
    ports:
      - "${USER_DB_PORT}:5432"
    networks:
      - backend_network

  postgres-workout:
    image: postgres:16
    container_name: postgres-workout
    environment:
      POSTGRES_USER: ${WORKOUT_DB_USER}
      POSTGRES_PASSWORD: ${WORKOUT_DB_PASSWORD}
    volumes:
      - pgdata-workout:/var/lib/postgresql/data
    ports:
      - "${WORKOUT_DB_PORT}:5432"
    networks:
      - backend_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - backend_network

  typesense:
    image: typesense/typesense:30.1
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redisdata:/var/lib/redis/
        

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata-user:
  pgdata-workout:
  rabbitmq_data:
